// This file is generated by GoAdmin CLI adm.
package pages

import (
	"admin/pages/AutoPages"
	"admin/pages/CustomPages"

	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "t_game_servers" => http://localhost:9033/admin/info/t_game_servers
// "log_character_chats" => http://localhost:9033/admin/info/log_character_chats
// "log_player_levelups" => http://localhost:9033/admin/info/log_player_levelups
// "log_player_quests" => http://localhost:9033/admin/info/log_player_quests
// "log_player_exps" => http://localhost:9033/admin/info/log_player_exps
// "log_player_moneys" => http://localhost:9033/admin/info/log_player_moneys
// "log_player_items" => http://localhost:9033/admin/info/log_player_items
// "log_player_dungeons" => http://localhost:9033/admin/info/log_player_dungeons
// "log_player_stone" => http://localhost:9033/admin/info/log_player_stone
// "log_player_equip" => http://localhost:9033/admin/info/log_player_equip
// "log_player_amulet" => http://localhost:9033/admin/info/log_player_amulet
// "log_player_ertl" => http://localhost:9033/admin/info/log_player_ertl
// "t_notices" => http://localhost:9033/admin/info/t_notices
// "t_function_switch" => http://localhost:9033/admin/info/t_function_switch
// "t_ip_rules" => http://localhost:9033/admin/info/t_ip_rules
// "t_activation_code" => http://localhost:9033/admin/info/t_activation_code
// "t_activation_code_use" => http://localhost:9033/admin/info/t_activation_code_use
// "t_affiche" => http://localhost:9033/admin/info/t_affiche
//
// example end
var Generators = map[string]table.Generator{

	"log_character_onlines":  AutoPages.GetLogCharacterOnlinesTable,
	"online_log":             AutoPages.GetLogCharacterLoginTable,
	"t_game_servers":         AutoPages.GetTGameServersTable,
	"log_character_chats":    AutoPages.GetLogCharacterChatsTable,
	"log_player_levelups":    AutoPages.GetLogPlayerLevelupsTable,
	"log_player_quests":      AutoPages.GetLogPlayerQuestsTable,
	"log_player_exps":        AutoPages.GetLogPlayerExpsTable,
	"log_player_moneys":      AutoPages.GetLogPlayerMoneysTable,
	"log_player_items":       AutoPages.GetLogPlayerItemsTable,
	"log_player_dungeons":    AutoPages.GetLogPlayerDungeonsTable,
	"log_player_stone":       AutoPages.GetLogPlayerStoneTable,
	"log_player_equip":       AutoPages.GetLogPlayerEquipTable,
	"log_player_amulet":      AutoPages.GetLogPlayerAmuletTable,
	"log_player_ertl":        AutoPages.GetLogPlayerErtlTable,
	"t_notices":              AutoPages.GetTNoticesTable,
	"inst_player_char_brief": AutoPages.GetPlayerBriefInfo,
	"ExportTables":           AutoPages.GetTestFilterForm,
	"TDataDetail":            CustomPages.GetTDataDetail,
	//"Retained4IP":               CustomPages.GetRetained4IP,
	//"Retained4Account":          CustomPages.GetRetained4Account,
	"t_function_switch":         AutoPages.GetTFunctionSwitchTable,
	"t_ip_rules":                AutoPages.GetTIpRulesTable,
	"t_activation_code":         AutoPages.GetTActivationCodeTable,
	"t_activation_code_use":     AutoPages.GetTActivationCodeUseTable,
	"RankList":                  AutoPages.GetRankList,
	"totalRechargeRankList":     AutoPages.GetTotalRechargeRankList,
	"t_affiche":                 AutoPages.GetTAfficheTable,
	"RealTimeOnline":            CustomPages.GetRealTimeOnline,
	"player_active_count":       AutoPages.GetPlayerActiveCountTable,
	"OnlineNumByHour":           CustomPages.GetOnlineNumByHour,
	"SingleSeverCount":          CustomPages.GetSingleSeverCount,
	"DeviceInfo":                CustomPages.GetDeviceInfo,
	"complaint_management":      AutoPages.GetComplaintManagementTable,
	"log_player_item_add_error": AutoPages.GetLogPlayerItemAddError,
	"global_cfg_check":          AutoPages.GetGlobalCfgCheckTable,
	"suspicious_data_record":    AutoPages.GetSuspiciousDataRecordTable,
	"t_account_characters":      AutoPages.GetTAccountCharactersTable,
	"t_exp_cfg":                 AutoPages.GetTExpCfgTable,
	"t_exp_config":              AutoPages.GetTExcelConfigTable,
	"operation_servers":         AutoPages.GetOperationServer,
	"operation_servers_pro":     AutoPages.GetOperationServerPro,
	"RankListPro":               AutoPages.GetRankListPro,
	"RankListAllServer":         AutoPages.GetRankListAllServer,
	"QueryExcellentCount":       AutoPages.QueryExcellentCount,
	"CCUByDate":                 CustomPages.GetCCUByDate,
	"AllServerCCUOneDay":        CustomPages.GetAllServerCCUOneDay,
	"GetAccountDataCountTable":  AutoPages.GetAccountDataCountTable,
	"TClientVersionTable":       AutoPages.GetTClientVersionTable,
	"GetRetrievePWDPage":        CustomPages.GetRetrievePWDPage,
	"Diamond4RebornRec":         CustomPages.GetDiamond4RebornRecTable,
	"BuyStoneFromShop":          CustomPages.GetBuyStoneFromShopTable,
	"PlayerCCU4Career":          CustomPages.GetPlayerCCU4Career,
	"Operationaudit":            AutoPages.GetOperationauditTable,
	"hotfix_data_tables":        CustomPages.GetHotfixDataTablesTable,
	// generators end
}
